name: CMake Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Set up MSVC
      run: |
        choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools"
        choco install ninja

    - name: Configure project with CMake
      run: cmake -S . -B build -G Ninja

    - name: Build project
      run: cmake --build build --parallel

    - name: Run tests
      run: ctest --test-dir build --output-on-failure
